#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDproductos")]
	public partial class DcMaterialesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCC(CC instance);
    partial void UpdateCC(CC instance);
    partial void DeleteCC(CC instance);
    #endregion
		
		public DcMaterialesDataContext() : 
				base(global::Clases.Properties.Settings.Default.BDproductosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DcMaterialesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcMaterialesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcMaterialesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DcMaterialesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Solicitud_m> Solicitud_m
		{
			get
			{
				return this.GetTable<Solicitud_m>();
			}
		}
		
		public System.Data.Linq.Table<Materiales> Materiales
		{
			get
			{
				return this.GetTable<Materiales>();
			}
		}
		
		public System.Data.Linq.Table<CC> CC
		{
			get
			{
				return this.GetTable<CC>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearMaterial")]
		public int CrearMaterial([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CC", DbType="NVarChar(50)")] string cC, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sku", DbType="NVarChar(50)")] string sku, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Desc", DbType="NVarChar(50)")] string desc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cant", DbType="Int")] System.Nullable<int> cant, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="NVarChar(10)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, cC, usuario, sku, desc, cant, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DarAprobacion")]
		public int DarAprobacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.emailCC")]
		public ISingleResult<emailCCResult> emailCC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO", DbType="NVarChar(10)")] string cODIGO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO);
			return ((ISingleResult<emailCCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingreso")]
		public ISingleResult<ingresoResult> ingreso([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string usu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string pas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usu, pas);
			return ((ISingleResult<ingresoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Solicitud_m")]
	public partial class Solicitud_m
	{
		
		private System.Nullable<int> _id_Solicitud;
		
		private string _CC;
		
		private string _Usuario;
		
		private string _Sku;
		
		private string _Descrip;
		
		private string _Cantidad;
		
		public Solicitud_m()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Solicitud", DbType="Int")]
		public System.Nullable<int> id_Solicitud
		{
			get
			{
				return this._id_Solicitud;
			}
			set
			{
				if ((this._id_Solicitud != value))
				{
					this._id_Solicitud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC", DbType="NVarChar(50)")]
		public string CC
		{
			get
			{
				return this._CC;
			}
			set
			{
				if ((this._CC != value))
				{
					this._CC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="NVarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sku", DbType="NVarChar(50)")]
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				if ((this._Sku != value))
				{
					this._Sku = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrip", DbType="NVarChar(50)")]
		public string Descrip
		{
			get
			{
				return this._Descrip;
			}
			set
			{
				if ((this._Descrip != value))
				{
					this._Descrip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="NVarChar(50)")]
		public string Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Materiales")]
	public partial class Materiales
	{
		
		private int _ID_materiales;
		
		private System.Nullable<int> _REFERENCIA;
		
		private string _DESCRIPCION;
		
		public Materiales()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_materiales", DbType="Int NOT NULL")]
		public int ID_materiales
		{
			get
			{
				return this._ID_materiales;
			}
			set
			{
				if ((this._ID_materiales != value))
				{
					this._ID_materiales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REFERENCIA", DbType="Int")]
		public System.Nullable<int> REFERENCIA
		{
			get
			{
				return this._REFERENCIA;
			}
			set
			{
				if ((this._REFERENCIA != value))
				{
					this._REFERENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NChar(50)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CC")]
	public partial class CC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_CC;
		
		private string _CC1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_CCChanging(int value);
    partial void OnId_CCChanged();
    partial void OnCC1Changing(string value);
    partial void OnCC1Changed();
    #endregion
		
		public CC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_CC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_CC
		{
			get
			{
				return this._Id_CC;
			}
			set
			{
				if ((this._Id_CC != value))
				{
					this.OnId_CCChanging(value);
					this.SendPropertyChanging();
					this._Id_CC = value;
					this.SendPropertyChanged("Id_CC");
					this.OnId_CCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CC", Storage="_CC1", DbType="NVarChar(50)")]
		public string CC1
		{
			get
			{
				return this._CC1;
			}
			set
			{
				if ((this._CC1 != value))
				{
					this.OnCC1Changing(value);
					this.SendPropertyChanging();
					this._CC1 = value;
					this.SendPropertyChanged("CC1");
					this.OnCC1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class emailCCResult
	{
		
		private string _GERENTE;
		
		private System.Nullable<int> _CODIGO;
		
		public emailCCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GERENTE", DbType="NVarChar(255)")]
		public string GERENTE
		{
			get
			{
				return this._GERENTE;
			}
			set
			{
				if ((this._GERENTE != value))
				{
					this._GERENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="Int")]
		public System.Nullable<int> CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
	}
	
	public partial class ingresoResult
	{
		
		private string _nombre;
		
		public ingresoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
